// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

function evenFib(n) {
  var sum = 0;
  var a = 1;
  var b = 2;
  var temp;
    while (b < n) {
      if (b % 2 === 0) {
        sum += b;
      }
      temp = a;
      a = b;
      b += temp;
    }
  return sum;
}

console.log(evenFib(4000000));
